name: CI Workflow

# Executa o workflow a cada commit ou quando houver um merge na branch main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código no repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração da versão do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instalação das dependências do projeto
      - name: Install dependencies
        run: npm install

      # Rodando o linting para verificar a qualidade do código
      - name: Run Linting
        run: npm run lint

      # Build do projeto para garantir que não haja erros de compilação
      - name: Build project
        run: npm run build

      # Enviando alerta para o Discord
      - name: Send Discord Alert
        if: always()  # Alerta em caso de sucesso ou falha
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "Build and tests completed!"}' https://discord.com/api/webhooks/1290083095252307979/Pz-fzPHsDdaxw7DWxz4oC9bBaFjGUVPpDQO9-UwbBzd2KpIWZrzkRy03Mz-t2Cq-f9xl
