name: CI Workflow

# Executa o workflow em push e pull request na branch main
on:
  push:
    branches: [main]  # Executa o workflow para cada commit na branch main
  pull_request:
    branches: [main]  # Executa o workflow quando há pull requests na branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código no repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Verifica se é um merge na branch main
      - name: Check if it's a merge
        id: check_merge
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"Merge pull request"* ]]; then
            echo "::set-output name=merge::true"
          else
            echo "::set-output name=merge::false"
          fi

      # Só envia alertas e executa processos se não for um merge
      - name: Send Discord Alert (Iniciando build)
        if: steps.check_merge.outputs.merge == 'false'
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "🔨 Iniciando o processo de build..."}' https://discord.com/api/webhooks/1290083095252307979/Pz-fzPHsDdaxw7DWxz4oC9bBaFjGUVPpDQO9-UwbBzd2KpIWZrzkRy03Mz-t2Cq-f9xl

      - name: Setup Node.js
        if: steps.check_merge.outputs.merge == 'false'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        if: steps.check_merge.outputs.merge == 'false'
        run: npm install

      - name: Send Discord Alert (Dependências instaladas)
        if: steps.check_merge.outputs.merge == 'false'
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "📦 Dependências instaladas com sucesso!"}' https://discord.com/api/webhooks/1290083095252307979/Pz-fzPHsDdaxw7DWxz4oC9bBaFjGUVPpDQO9-UwbBzd2KpIWZrzkRy03Mz-t2Cq-f9xl

      - name: Run Linting
        if: steps.check_merge.outputs.merge == 'false'
        run: npm run lint

      - name: Send Discord Alert (Linting concluído)
        if: steps.check_merge.outputs.merge == 'false'
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "✅ Linting concluído! O código está limpo."}' https://discord.com/api/webhooks/1290083095252307979/Pz-fzPHsDdaxw7DWxz4oC9bBaFjGUVPpDQO9-UwbBzd2KpIWZrzkRy03Mz-t2Cq-f9xl

      - name: Build project
        if: steps.check_merge.outputs.merge == 'false'
        run: npm run build

      - name: Send Discord Alert (Build concluído)
        if: steps.check_merge.outputs.merge == 'false'
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "🚀 Build concluído com sucesso!"}' https://discord.com/api/webhooks/1290083095252307979/Pz-fzPHsDdaxw7DWxz4oC9bBaFjGUVPpDQO9-UwbBzd2KpIWZrzkRy03Mz-t2Cq-f9xl

      # Envia alerta específico quando houver um merge na branch main
      - name: Send Discord Alert (Merge na branch main)
        if: steps.check_merge.outputs.merge == 'true'
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "🔀 Merge realizado na branch main!"}' https://discord.com/api/webhooks/1290083095252307979/Pz-fzPHsDdaxw7DWxz4oC9bBaFjGUVPpDQO9-UwbBzd2KpIWZrzkRy03Mz-t2Cq-f9xl
