name: CI Workflow

# Executa o workflow em pull request na branch main
on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código no repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Enviar mensagem de início ao Discord
      - name: Send Start Message to Discord
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "🔨 CI: Iniciando o processo de build..."}' https://discord.com/api/webhooks/1290083095252307979/Pz-fzPHsDdaxw7DWxz4oC9bBaFjGUVPpDQO9-UwbBzd2KpIWZrzkRy03Mz-t2Cq-f9xl

      # Instalação das dependências
      - name: Install dependencies
        run: |
          npm install
          curl -H "Content-Type: application/json" -X POST -d '{"content": "📦 CI: Dependências instaladas com sucesso!"}' https://discord.com/api/webhooks/1290083095252307979/Pz-fzPHsDdaxw7DWxz4oC9bBaFjGUVPpDQO9-UwbBzd2KpIWZrzkRy03Mz-t2Cq-f9xl

      # Executar linting
      - name: Run Linting
        run: |
          npm run lint
          curl -H "Content-Type: application/json" -X POST -d '{"content": "✅ CI: Linting concluído! O código está limpo."}' https://discord.com/api/webhooks/1290083095252307979/Pz-fzPHsDdaxw7DWxz4oC9bBaFjGUVPpDQO9-UwbBzd2KpIWZrzkRy03Mz-t2Cq-f9xl

      # Executar testes unitários
      - name: Run Tests
        run: |
          npm test -- --watchAll=false
          curl -H "Content-Type: application/json" -X POST -d '{"content": "🧪 CI: Testes executados com sucesso!"}' https://discord.com/api/webhooks/1290083095252307979/Pz-fzPHsDdaxw7DWxz4oC9bBaFjGUVPpDQO9-UwbBzd2KpIWZrzkRy03Mz-t2Cq-f9xl

      # Build do projeto
      - name: Build project
        run: |
          npm run build
          curl -H "Content-Type: application/json" -X POST -d '{"content": "🚀 CI: Build concluído com sucesso!"}' https://discord.com/api/webhooks/1290083095252307979/Pz-fzPHsDdaxw7DWxz4oC9bBaFjGUVPpDQO9-UwbBzd2KpIWZrzkRy03Mz-t2Cq-f9xl
