name: CI Workflow

# Executa o workflow sempre que houver pull request na branch principal
on:
  pull_request:
    branches: [main]

# Define o ambiente onde o workflow será executado
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código no repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração da versão do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instalação das dependências do projeto
      - name: Install dependencies
        run: npm install

      # Rodando o linting para verificar a qualidade do código
      - name: Run Linting
        run: npm run lint

      # Build do projeto para garantir que não haja erros de compilação
      - name: Build project
        run: npm run build