name: CI Workflow

# Executa o workflow a cada commit ou quando houver um merge na branch main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código no repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração da versão do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instalação das dependências do projeto
      - name: Install dependencies
        run: npm install

      # Rodando o linting para verificar a qualidade do código
      - name: Run Linting
        id: linting
        run: npm run lint

      # Build do projeto para garantir que não haja erros de compilação
      - name: Build project
        id: build
        run: npm run build

      # Enviando alertas para o Discord
      - name: Send Discord Alert
        if: always()  # Alerta em caso de sucesso ou falha
        run: |
          # Mensagens personalizadas
          MESSAGE=""

          # Verificando se o linting foi bem-sucedido (envia mensagem apenas se NÃO for merge de PR)
          if [[ "${{ github.event_name }}" != "pull_request" ]]; then
            MESSAGE+="CI Workflow Executado!\n"
            if [[ "${{ steps.linting.outcome }}" == "success" ]]; then
              MESSAGE+="Linting realizado com sucesso! 🎉\n"
            else
              MESSAGE+="Erro no linting! ❌\n"
            fi

            # Verificando se o build foi bem-sucedido
            if [[ "${{ steps.build.outcome }}" == "success" ]]; then
              MESSAGE+="Build realizado com sucesso! 🎉\n"
            else
              MESSAGE+="Erro no build! ❌\n"
            fi
          fi

          # Mensagem adicional para informar que o processo foi iniciado (em caso de merge ou commit)
          if [[ "${{ github.event_name }}" == "pull_request" ]] && [[ "${{ github.event.action }}" == "closed" ]] && [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            MESSAGE+="Processo iniciado por um merge de pull request na branch principal. 📝\n"
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            MESSAGE+="Processo iniciado por um commit na branch principal. 📝\n"
          fi

          # Enviando a mensagem para o Discord
          if [[ ! -z "$MESSAGE" ]]; then
            curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"$MESSAGE\"}" https://discord.com/api/webhooks/1290083095252307979/Pz-fzPHsDdaxw7DWxz4oC9bBaFjGUVPpDQO9-UwbBzd2KpIWZrzkRy03Mz-t2Cq-f9xl
          fi
