name: CI Workflow

# Executa o workflow em push e pull request na branch main
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código no repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Verifica se é um merge na branch main
      - name: Check if it's a merge
        id: check_merge
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.action }}" == "closed" && "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "::set-output name=merge::true"
          else
            echo "::set-output name=merge::false"
          fi

      # Passo para instalar dependências e construir o projeto, mas sem enviar alertas durante o merge
      - name: Install dependencies
        if: steps.check_merge.outputs.merge == 'false'
        run: npm install

      - name: Run Linting
        if: steps.check_merge.outputs.merge == 'false'
        run: npm run lint

      - name: Build project
        if: steps.check_merge.outputs.merge == 'false'
        run: npm run build

      # Este passo é para indicar que um merge foi realizado, mas não envia alertas
      - name: No alert on merge
        if: steps.check_merge.outputs.merge == 'true'
        run: echo "Merge realizado, não enviaremos alertas de CI."

