name: CI Workflow

# Executa o workflow a cada commit ou quando houver um merge na branch main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código no repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração da versão do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instalação das dependências do projeto
      - name: Install dependencies
        run: npm install

      # Rodando o linting para verificar a qualidade do código
      - name: Run Linting
        id: linting  # Adicionando um ID para referenciar depois
        run: npm run lint

      # Build do projeto para garantir que não haja erros de compilação
      - name: Build project
        id: build  # Adicionando um ID para referenciar depois
        run: npm run build

      # Validando se o delivery.yml rodou sem erros
      - name: Check Delivery Workflow
        id: check_delivery
        run: |
          # Verifica se o arquivo delivery.yml rodou corretamente
          echo "Checking delivery workflow..."
          # Substitua pelo comando que verifica o sucesso do delivery.yml
          # Aqui, você pode verificar os logs ou status da execução anterior conforme necessário.
          # Por exemplo:
          # if [[ $(some_command_to_check_delivery_status) != "success" ]]; then
          #   echo "Delivery workflow failed!" && exit 1
          # fi

      # Enviando alertas para o Discord
      - name: Send Discord Alert
        if: always()  # Alerta em caso de sucesso ou falha
        run: |
          # Mensagens personalizadas
          MESSAGE=""

          # Verificando se o delivery workflow foi bem-sucedido
          if [[ "${{ steps.check_delivery.outcome }}" == "success" ]]; then
            MESSAGE+="Delivery workflow succeeded! 🎉\n"
          else
            MESSAGE+="Delivery workflow failed! ❌\n"
          fi

          if [[ "${{ steps.linting.outcome }}" == "success" ]]; then
            MESSAGE+="Linting passed! 🎉\n"
          else
            MESSAGE+="Linting failed! ❌\n"
          fi

          if [[ "${{ steps.build.outcome }}" == "success" ]]; then
            MESSAGE+="Build succeeded! 🎉\n"
          else
            MESSAGE+="Build failed! ❌\n"
          fi

          # Mensagem adicional para informar que o processo foi iniciado
          if [[ "${{ github.event_name }}" == "push" ]]; then
            MESSAGE+="Process initiated by a commit to the main branch. 📝\n"
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            MESSAGE+="Process initiated by a pull request merge to the main branch. 📝\n"
          fi

          # Enviando a mensagem para o Discord
          curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"$MESSAGE\"}" https://discord.com/api/webhooks/1290083095252307979/Pz-fzPHsDdaxw7DWxz4oC9bBaFjGUVPpDQO9-UwbBzd2KpIWZrzkRy03Mz-t2Cq-f9xl
