name: CI Workflow

# Executa o workflow em push e pull request na branch main
on:
  push:
    branches: [main]  # Executa o workflow para cada commit na branch main
  pull_request:
    branches: [main]  # Executa o workflow quando há pull requests na branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código no repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Envia alerta de início do processo de build
      - name: Send Discord Alert (Iniciando build)
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "🔨 Iniciando o processo de build..."}' https://discord.com/api/webhooks/1290083095252307979/Pz-fzPHsDdaxw7DWxz4oC9bBaFjGUVPpDQO9-UwbBzd2KpIWZrzkRy03Mz-t2Cq-f9xl

      # Configuração da versão do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instalação das dependências do projeto
      - name: Install dependencies
        run: npm install

      # Envia alerta quando as dependências forem instaladas
      - name: Send Discord Alert (Dependências instaladas)
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "📦 Dependências instaladas com sucesso!"}' https://discord.com/api/webhooks/1290083095252307979/Pz-fzPHsDdaxw7DWxz4oC9bBaFjGUVPpDQO9-UwbBzd2KpIWZrzkRy03Mz-t2Cq-f9xl

      # Rodando o linting para verificar a qualidade do código
      - name: Run Linting
        run: npm run lint

      # Envia alerta quando o linting for concluído
      - name: Send Discord Alert (Linting concluído)
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "✅ Linting concluído! O código está limpo."}' https://discord.com/api/webhooks/1290083095252307979/Pz-fzPHsDdaxw7DWxz4oC9bBaFjGUVPpDQO9-UwbBzd2KpIWZrzkRy03Mz-t2Cq-f9xl

      # Build do projeto para garantir que não haja erros de compilação
      - name: Build project
        run: npm run build

      # Envia alerta quando o build for concluído
      - name: Send Discord Alert (Build concluído)
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "🚀 Build concluído com sucesso!"}' https://discord.com/api/webhooks/1290083095252307979/Pz-fzPHsDdaxw7DWxz4oC9bBaFjGUVPpDQO9-UwbBzd2KpIWZrzkRy03Mz-t2Cq-f9xl

      # Envia alerta específico quando houver um merge na branch main
      - name: Send Discord Alert (Merge na branch main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "🔀 Merge realizado na branch main!"}' https://discord.com/api/webhooks/1290083095252307979/Pz-fzPHsDdaxw7DWxz4oC9bBaFjGUVPpDQO9-UwbBzd2KpIWZrzkRy03Mz-t2Cq-f9xl
